### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by piroyuki666** [piroyuki666/protospace-38024#1]
https://protospace-38024.herokuapp.com/
よろしくお願いします。

**Comment by shodai-ito** [comment]
@piroyuki666 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されていること**
敬称が省略されているので「〇〇さん」と表示されるようにしましょう！

- [x] **ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから編集ボタンをクリックすると、編集ページへ遷移できること**
編集ページに遷移できませんでした。

- [x] **ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから削除ボタンをクリックすると、プロトタイプを削除できること**
削除ボタンを押すと、対象以外のプロトタイプが削除されます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by piroyuki666** [comment]
修正いたしました、再度確認をお願い致します。
https://protospace-38024.herokuapp.com/

**Comment by shodai-ito** [comment]
@piroyuki666 さん、再度ご提出ありがとうございます‼︎
指摘箇所の修正確認いたしました！
しかしながら、一部改めて修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから編集ボタンをクリックすると、編集ページへ遷移できること**
編集ボタンを押してもトップページへ遷移してしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by piroyuki666** [comment]
すみません、確認が甘かったです、、、改めて修正しました。確認をお願いいたしますhttps://protospace-38024.herokuapp.com/

**Comment by shodai-ito** [comment]
@piroyuki666 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。

**Comment by piroyuki666** [comment]
ありがとうございます。今回の経験を最終課題、オリジナルアプリ制作に活かします
